version: "2"
run:
  tests: true
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - bodyclose
    - canonicalheader
    - copyloopvar
    - dogsled
    - errcheck
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - maintidx
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - perfsprint
    - promlinter
    - protogetter
    - revive
    - staticcheck
    - tagalign
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - zerologlint
  settings:
    dogsled:
      max-blank-identifiers: 6
    gosec:
      includes:
        - G102
        - G103
        - G104
        - G106
        - G107
        - G108
        - G109
        - G110
        - G111
        - G112
        - G113
        - G114
        - G201
        - G202
        - G203
        - G204
        - G301
        - G302
        - G303
        - G304
        - G305
        - G306
        - G307
        - G401
        - G402
        - G403
        - G404
        - G501
        - G502
        - G503
        - G504
        - G505
        - G601
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - server/grpc/gogoreflection/fix_registration.go
      - x/wasm/migrations/v2/legacy_types.go
      - .*\.pb\.go$
      - .*\.pb\.gw\.\.go$
      - .*\.pulsar\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(cosmossdk.io)
        - prefix(github.com/cosmos/cosmos-sdk)
        - prefix(github.com/CosmWasm/wasmd)
      custom-order: true
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - server/grpc/gogoreflection/fix_registration.go
      - x/wasm/migrations/v2/legacy_types.go
      - .*\.pb\.go$
      - .*\.pb\.gw\.\.go$
      - .*\.pulsar\.go$
      - third_party$
      - builtin$
      - examples$
